w3c/at-driver

README.md
Contrary to what this document originally claimed, there is a WebDriver
command which is capable of simulating a "key press" without any
particular target element: "Perform Actions."
Remove the inaccurate argument from the explanation.
Resolves gh-5
=> Remove inaccurate argument

.gitignore, index.bs, package-lock.json, package.json, schemas/at-driver-local.cddl, schemas/at-driver-local.json, schemas/at-driver-remote.cddl, schemas/at-driver-remote.json, scripts/extract-schemas.js
A start of milestone 0 in https://github.com/w3c/aria-at-automation/issues/15
This is modeled after the WebDriver BiDi spec: https://w3c.github.io/webdriver-bidi/
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/19.html" title="Last updated on Aug 16, 2022, 12:23 PM UTC (670fcab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/19/22d3c12...670fcab.html" title="Last updated on Aug 16, 2022, 12:23 PM UTC (670fcab)">Diff</a>
=> Initial draft

index.bs, schemas/at-driver-local.cddl
This text was added in #25 and was accidentally removed when merging #22.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/31.html" title="Last updated on Oct 19, 2022, 1:36 PM UTC (9b7952e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/31/818d942...9b7952e.html" title="Last updated on Oct 19, 2022, 1:36 PM UTC (9b7952e)">Diff</a>
=> Add back 'capture output' section

index.bs, schemas/at-driver-remote.cddl
API to simulate keypresses. Milestone 3 in #15
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/26.html" title="Last updated on Nov 22, 2022, 12:11 AM UTC (8009bfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/26/9faba32...8009bfc.html" title="Last updated on Nov 22, 2022, 12:11 AM UTC (8009bfc)">Diff</a>
=> Keypresses

index.bs
"Commands" are generally described to include a "result type," but none of the commands defined actually include such a value. They do include a "return type," as defined by WEBIDL. Since WEBIDL's "return type" does not seem particularly relevant and since the terms "result type" and "return type" have similar connotations in this context, this appears to be an editorial oversight.
Update the command definitions to specify a "result type," and update the explanation of the commands' "remote end steps" to return an instance of the "result type."
See also the corresponding change to the WebDriver BiDi proposal: https://github.com/w3c/webdriver-bidi/pull/192
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/37.html" title="Last updated on Nov 29, 2022, 1:10 AM UTC …
=> Editorial: Correct references to "result type"

index.bs
These invalid references are reported as a "link error" by the Bikeshed build tool:
LINK ERROR: No 'dfn' refs found for 'error' with for='['command']'.
<a data-link-for="command" data-link-type="dfn" data-lt="error">error</a>
Correct the references so that the links are rendered correctly.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/39.html" title="Last updated on Dec 13, 2022, 2:44 AM UTC (03e4501)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/39/6946c03...03e4501.html" title="Last updated on Dec 13, 2022, 2:44 AM UTC (03e4501)">Diff</a>
=> Editorial: Correct references to "error"

index.bs
Prior to this patch, the variable "session" was referenced without being declared. Although the WebDriver BiDi specification includes a rich concept of event subscriptions [1], this proposal uses a much less expressive model. Notably, a remote end only has a single active session at any given moment.
Define the "session" variable to take the value of the one and only active session.
[1] https://w3c.github.io/webdriver-bidi/#command-session-subscribe
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/47.html" title="Last updated on Nov 29, 2022, 9:17 PM UTC (54c3ef1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/47/6e490f2...54c3ef1.html" title="Last updated on Nov 29, 2022, 9:17 PM UTC (54c3ef1)">Diff</a>
=> Editorial: define variable in event algorithm

index.bs
- Reference the input parameters by name rather than by type.
- Delineate implementation-defined behavior in dedicated steps.
- Specify a return value for successful operations.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/41.html" title="Last updated on Nov 29, 2022, 7:41 PM UTC (3215292)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/41/6e490f2...3215292.html" title="Last updated on Nov 29, 2022, 7:41 PM UTC (3215292)">Diff</a>
=> Normative: formalize "interaction.pressKeys" steps

.github/workflows/auto-publish.yml, index.bs
Prior to this commit, the continuous integration system tolerated faulty references which the Bikeshed tool refers to as "link errors" [^1]. This has allowed at least one editorial oversight to be accepted to the `main` branch and subsequently published [^2].
Configure the GitHub Action which wraps Bikeshed [^3] to reject pull requests which introduce faulty references.
[^1]: https://tabatkins.github.io/bikeshed/#cli-options  
[^2]: https://github.com/w3c/aria-at-automation/pull/19  
[^3]: https://github.com/w3c/spec-prod/blob/main/docs/options.md#build_fail_on
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/61.html" title="Last updated on Dec 19, 2022, 10:59 PM UTC (2fc6713)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/61/ …
=> Meta: reject "link errors" in CI

index.bs
The proposal defines "error" as an internal type for describing one kind of result of fallible algorithms, and it defines "ErrorResponse" as a type of message which may be sent to clients. The algorithm used to transmit error responses to clients is named "respond with an error" even though it does not use the "error" type.
Rename "respond with an error" to "send an error response" to more accurately describe the types involved.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/56.html" title="Last updated on Jan 24, 2023, 12:33 AM UTC (c336024)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/56/3ad852c...c336024.html" title="Last updated on Jan 24, 2023, 12:33 AM UTC (c336024)">Diff</a>
=> Editorial: rename "respond with an error"

index.bs
Add references to the definitions of the terms "module" and "command type." This justifies the definitions, supports new readers, and suppresses two instances of the following warning from the Bikeshed build tool:
>     WARNING: Unexported dfn that's not referenced locally - did you mean to export it?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/57.html" title="Last updated on Dec 13, 2022, 6:09 PM UTC (5695d2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/57/26e83e2...5695d2b.html" title="Last updated on Dec 13, 2022, 6:09 PM UTC (5695d2b)">Diff</a>
=> Editorial: add references to definitions

index.bs
The algorithm for the "session.new" command includes a guard for the case where an active session already exists:
> 2. If the list of [=active sessions=] is not empty, then return [=error=] with error code [=session not created=].
Prior to this commit, sessions were not removed from this list when they were depleted of connections. Following the creation and termination of some initial connection, a remote end would forever deny further requests to create new sessions.
Destroy the active session when its final connection is closed so that a new session may be subsequently created.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/60.html" title="Last updated on Dec 14, 2022, 3:06 AM UTC (03b03a5)">Preview</a> | <a …
=> Normative: destroy sessions with zero connections

index.bs, schemas/at-driver-local.cddl, schemas/at-driver-remote.cddl
The name "Extensible" more clearly communicates the intent of the pattern which is used repeatedly in defining other types in the specification.
Resolves gh-28.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/66.html" title="Last updated on Dec 22, 2022, 10:33 PM UTC (e090379)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/66/3ad852c...e090379.html" title="Last updated on Dec 22, 2022, 10:33 PM UTC (e090379)">Diff</a>
=> Editorial: define "Extensible" type

index.bs
The "handle an incoming message" algorithm expects every command to return either a "success" value or an "error" value:
>     1. Let |result| be the result of running the [=remote end steps=] for |command| given |session| and [=command parameters=] |matched|["`params`"].
>     2. If |result| is an [=error=], then [=respond with an error=] given |connection|, |command id|, and |result|'s [=error code=], and finally return.
>     3. Let |value| be |result|'s data.
Update the "interaction.pressKeys" algorithm to satisfy this expectation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/67.html" title="Last updated on Jan 3, 2023, 11:19 PM UTC (8c18b91)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/67/3ad852c...8c18b91.html" …
=> Editorial: correct command return value

index.bs
Correct the derivation of "required capabilities" and simplify the return value.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/55.html" title="Last updated on Dec 13, 2022, 3:00 AM UTC (6b31f7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/55/26e83e2...6b31f7e.html" title="Last updated on Dec 13, 2022, 3:00 AM UTC (6b31f7e)">Diff</a>
=> Editorial: Correct "process capabilities" algorithm

index.bs, schemas/at-driver-local.cddl, schemas/at-driver-local.json, schemas/at-driver-remote.cddl, schemas/at-driver-remote.json
Replace the templated "extension module" with a single concrete module for all vendors named settings. This improves the maintainability of the proposal and the usability of the protocol without meaningfully limiting implementation freedom or future protocol revisions.
Depends on gh-58. Resolves gh-48.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/pull/65.html" title="Last updated on Mar 29, 2023, 1:54 AM UTC (9f76a26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-at-automation/65/acbf00d...9f76a26.html" title="Last updated on Mar 29, 2023, 1:54 AM UTC (9f76a26)">Diff</a>
=> Normative: remove prefix from settings module

index.bs
In describing the absence of validity, the algorithm named "setting name is invalid" was difficult to reason about. Although an algorithm designed to report on positive validity (e.g. one named "setting name is valid") would be both more traditional and easier to understand, it would also suggest inaccurate state in certain implementations. Specifically, in implementations which cannot reject unrecognized setting names, an algorithm titled "setting name is valid" would claim that any arbitrary setting name is "valid."
Refactor the algorithm to return one of three values to accurately describe the result and avoid misleading call sites.
---
@jkva This is the best I could come up with following [our discussion in gh-54](https://github.com/w3c/aria-at-automation/pull/54#discussion_r1052669178 …
=> Editorial: refactor setting name validation

index.bs, schemas/at-driver-remote.cddl
In conversation with assistive technology vendors, we have learned that automating arbitrary key presses does not necessarily align with the security model of all platforms. Separately, we anticipate introducing means to simulate more specific types of user interaction (e.g. "move to next heading"). Because these may themselves be implemented at the vendor's discretion (and because we wish to allow for vendors to experiment with the development of still more kinds of interaction), the space for simulating interaction may be somewhat fragmented, particularly in the initial deployments of this protocol. We have decided to design a command which accommodates this variability so that the presence/absence of interactions can be communicated consistently (note the "unknown user intent" error) …
=> Refactor "pressKeys" as one of many "user intents"

w3c.json
The file is needed for tools to associate the repository with the group, and in particular to have the repository under the group's list of repositories in https://www.w3.org/groups/wg/browser-tools-testing/tools/
See documentation at: https://w3c.github.io/w3c.json.html
=> Add missing w3c.json file

.github/workflows/auto-publish.yml
Bikeshed now requires Python >= 3.9, which in turn requires moving to a more recent version of Ubuntu. Using "latest" here as that's unlikely going to ever trigger an issue. Also using that opportunity to bump versions of other actions used in the workflow.
=> Bump versions of dependencies used in workflow

index.bs, schemas/at-driver-local.cddl, schemas/at-driver-remote.cddl
The first rule in a CDDL document defines the entry point to validate a CBOR data item. The CDDL of each module started with `Extensible`, which essentially made any CBOR data item valid.
This update makes `Command` and `Message` the first CDDL rules in each module (as done in WebDriver BiDi), and defines `Extensible` is a single block common to both the remote end and local end definitions.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/at-driver/pull/83.html" title="Last updated on Dec 18, 2024, 2:55 AM UTC (de116f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/at-driver/83/fdb685b...tidoust:de116f7.html" title="Last updated on Dec 18, 2024, 2:55 AM UTC (de116f7)">Diff</a>
=> Re-order CDDL definitions so that Command / Message are first

index.bs
See https://github.com/w3c/webdriver-bidi/pull/831 for background.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/at-driver/pull/85.html" title="Last updated on Dec 19, 2024, 8:33 PM UTC (b519b6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/at-driver/85/7cb6e57...tidoust:b519b6c.html" title="Last updated on Dec 19, 2024, 8:33 PM UTC (b519b6c)">Diff</a>
=> Use `<code>` for references to a CDDL type
